require 'rails_helper'

RSpec.describe User, type: :model do

  it 'detects the autogenerated album user' do
    album = create(:album)
    expect(album.users.last.is_album_user?).to be true
  end

  it 'detects that other users of the album are not the album user' do
    album = create(:album)
    user = create(:user)
    album.users << user
    expect(album.users.last.is_album_user?).to be false
  end

end
